240825_2
olive-study-club/study-forever pull request #23
Opened 2024-08-25 08:06 UTC by Yul0201

wpf winform 누락분 수정해서 pr드립니다

2024-08-26 23:54 UTC, firewoody237 requested changes

2024-08-26 23:54 UTC, firewoody237 commented on yugenen84/System Outline/CS/WPF Winform.md
> +- 윈폼은 이벹느 기반 프로그래밍을 지원하며 다양한 컨트롤과 컴포넌트를 제공함
오타있네요

2024-08-26 23:54 UTC, firewoody237 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    - 다양한 디바이스 동작할 수 있으며 윈도우 전체를 사용하지 않고 UI를 커스터 마이징 할 수 있음
이 문장은 무슨뜻인가요??

2024-08-26 23:54 UTC, firewoody237 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    - 데이터 바인딩 기능을 제공하여 UI를 쉽게 연결할 수 있으며 데이터를 처리하는 로직과 UI를 만드는 디자인을 분리하여 개발의 효율성을 확보할 수 있음
이건 무슨패턴으로 ui와 로직을 분리해서 쓸까요?

2024-08-26 23:54 UTC, firewoody237 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    -
의미없는 문법이 들어가있어요

2024-08-28 04:20 UTC, Yul0201 commented on yugenen84/System Outline/CS/WPF Winform.md
> +- 윈폼은 이벹느 기반 프로그래밍을 지원하며 다양한 컨트롤과 컴포넌트를 제공함
넵 수정 pr 드리겠습니다

2024-08-28 04:20 UTC, Yul0201 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    - 다양한 디바이스 동작할 수 있으며 윈도우 전체를 사용하지 않고 UI를 커스터 마이징 할 수 있음
xaml 이라는 마크업을 정의하는 언어로 UI 를 구현하는 데 있어서 사용자가 임의로 정해서 표현하는 언어 형식입니다.

2024-08-28 04:20 UTC, Yul0201 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    - 데이터 바인딩 기능을 제공하여 UI를 쉽게 연결할 수 있으며 데이터를 처리하는 로직과 UI를 만드는 디자인을 분리하여 개발의 효율성을 확보할 수 있음
MVVM 패턴(Model, View, View Model) 입니다.

2024-08-28 04:20 UTC, Yul0201 commented on yugenen84/System Outline/CS/WPF Winform.md
> +    -
넵 삭제하겠습니다.

2024-08-28 04:23 UTC, firewoody237 approved these changes

2024-08-28 04:26 UTC, merged