system
olive-study-club/study-forever pull request #6
Opened 2024-07-21 06:17 UTC by Yul0201

인덱서에 공부했는데 프로퍼티랑 좀 더 비교해서 공부하고 추가 pr 드리겠습니다.

2024-07-21 09:06 UTC, firewoody237 commented on yugenen84/System/Csharp_Index.md
> +    ```C#
닫는 Markdown이 없네요

2024-07-21 09:56 UTC, firewoody237 requested changes
[Package Name Convention](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces)
패키지 이름은 C#의 경우 대문자로 시작하는 카멜케이스를 보통 사용합니다.

마크다운 문법 한번 복습하시고 쓰셔야겠어요.

2024-07-21 09:56 UTC, firewoody237 commented on yugenen84/System/Csharp_Index.md
> +    var a instance[0];
문법 틀렸습니다.

2024-07-21 09:56 UTC, firewoody237 commented on yugenen84/System/Csharp_Index.md
> +- 인텍싱 값은 형식이나 인스턴스 멤버를 명시적으로 지정하지 않고 설정하고 검색할 수 있음
```suggestion
- 인덱싱 값은 형식이나 인스턴스 멤버를 명시적으로 지정하지 않고 설정하고 검색할 수 있음
```

오타..

2024-07-21 09:56 UTC, firewoody237 commented on yugenen84/System/Csharp_Index.md
> +- 인텍싱 값은 형식이나 인스턴스 멤버를 명시적으로 지정하지 않고 설정하고 검색할 수 있음
> 인텍싱 값은 형식이나 인스턴스 멤버를 명시적으로 지정하지 않고 설정하고 검색할 수 있음

이건 무슨 의미인가요?

2024-07-21 09:56 UTC, firewoody237 commented on yugenen84/System/Csharp_Index.md
> +- 인덱서는 내부 컬렉션 또는 배열을 캡슐화하는데 주로 사용되는 형식에서 자주 구현됨
캡슐화가 무엇인지 알고 계신가요?

2024-07-22 14:02 UTC, merged

2024-07-24 05:23 UTC, Yul0201 commented on yugenen84/System/Csharp_Index.md
> +    ```C#
변경했습니다