no message
olive-study-club/study-forever pull request #9
Opened 2024-08-03 06:12 UTC by Yul0201

# 240803

-  cpu 스케쥴러
- 가상 메모리
- 데드락

2024-08-04 00:33 UTC, firewoody237 requested changes
커밋 메시지 신경써달라고 지난 PR에 말씀드렸었는데,
보고계신걸까요?

2024-08-04 00:43 UTC, firewoody237 reviewed
이 코멘트로 드린 내용은
수정하시거나, 아니면 세션에서 답변해주시면 될 것 같습니다~
쉬운 내용 아니였을텐데 고생하셨습니다 ㅎㅎ

2024-08-04 00:43 UTC, firewoody237 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +          - RR(Round robin) : 모든 프로세스가 같은 우선순위를 가지고 time slice를 기반으로 스케쥴링 함. time slice burst가 일어나면 해당 프로세스는 스케쥴링 큐의 끝으로 이동
burst는 문맥상 "완료"로 보이는데요, 어떤 뜻에서 유래된걸까요?

그리고 내용에서 "burst time" "버스트 시간" "버스트 타임"와 같이 같은용어임에도 여러가지고 산재한 느낌이 드네요.

2024-08-04 00:43 UTC, firewoody237 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +     - 우선 순위 스케쥴링
우선순위를 활용하는 거라면, 선점 스케줄링과 어떻게 다른걸까요?
(비선점, 선점, 우선순위가 같은 레벨로 레벨링 되어있어 질문드립니다)

2024-08-04 00:43 UTC, firewoody237 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +    - 페이징 테이블을 통해서 메인 메모리에 접근
세션에서 설명해 주실때 페이징 테이블 동작 순서도 같이 설명 부탁드려요~
저도 헷갈리는 내용 같아서요

2024-08-04 00:43 UTC, firewoody237 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +- 프로세스가 자원을 얻지 못해 다음 작업을 못하는 상태
그러면 데드락을 해제하고자 하면 어떻게 해야 하나요?

2024-08-04 00:43 UTC, firewoody237 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +- 준비 QUEUE에 있는 프로세스에 대해 CPU 할당하는 방법
혹시 "기아 상태"에 대한 내용도 이 내용과 관련있는데, 공부하셨을까요?

2024-08-06 23:35 UTC, Yul0201 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +          - RR(Round robin) : 모든 프로세스가 같은 우선순위를 가지고 time slice를 기반으로 스케쥴링 함. time slice burst가 일어나면 해당 프로세스는 스케쥴링 큐의 끝으로 이동
- Burst time 은 "어떤 오퍼레이션을 수행하는데 있어서 걸린시간"의 의미로 작성하였습니다.
- 용어에 대한 정리는 주의하면서 작성하겠습니다

2024-08-06 23:36 UTC, Yul0201 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +- 준비 QUEUE에 있는 프로세스에 대해 CPU 할당하는 방법
다음 주제로 공부해 보겠습니다

2024-08-06 23:38 UTC, Yul0201 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +- 프로세스가 자원을 얻지 못해 다음 작업을 못하는 상태
- 예방 또는 회피
- 상태 탐지 및 복구
- 무시
의 방법으로 진행되는 것으로 알고 있으나 세부적인 내용은 별도 주제로 올리겠습니다

2024-08-06 23:39 UTC, Yul0201 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +     - 우선 순위 스케쥴링
코멘트 주신 사항 별도로 공부해서 올리겠습니다

2024-08-06 23:48 UTC, Yul0201 commented on yugenen84/System Outline/Markdown/메모리구조.md
> +    - 페이징 테이블을 통해서 메인 메모리에 접근
<img width="633" alt="image" src="https://github.com/user-attachments/assets/ffaf219e-32b9-437c-83d6-077888f70c8e">

프로세스가 작업을 처리하기 위해 cpu에게 가상 주소를 넘겨주고 cpu는 그 가상 주소를 받아 실제 데이터를 찾는 걸로 이해하고 있습니다. 다만 공부가 더 필요할 것으로 보여서 추가적으로 공부해서 올리겠습니다.

2024-08-07 04:12 UTC, merged

2024-08-21 06:39 UTC, Yul0201 commented
> 커밋 메시지 신경써달라고 지난 PR에 말씀드렸었는데, 보고계신걸까요?

asadfs